### ISSUE TITLE
Call method execSql throwed NPE

### ISSUE THREAD

**Issue by VladislavK777** [Restream/reindexer-java#55]
При попытке выполнить нативный запрос получаем NPE.

`db.execSql("SELECT * FROM task_view", TaskView.class);`

```
Exception in thread "main" java.lang.NullPointerException
	at ru.rt.restream.reindexer.Reindexer.execSql(Reindexer.java:252)
	at com.example.demo.TaskView.main(TaskView.java:92)
```

`long [] ptVersions = new long[] {namespace.getPayloadType().getVersion()};`
При этом через db.query нормально работает.

И сразу вопрос, можно ли пользоваться оператором LIKE и как?
еще интересно, зачем ищется from без ignoreCase if ("FROM".equals(word)) ? Это особенность какая-то?

**Comment by steleal** [comment]
Пользоваться LIKE можно, примерно так:
"SELECT * FROM task_view WHERE some_field LIKE '%substring%'"

> еще интересно, зачем ищется from без ignoreCase if ("FROM".equals(word)) ? Это особенность какая-то?
Это баг.

По поводу NPE - как получить доступ к коду примера и к бд? 
Если коннектор не правили под себя, то NPE на  Reindexer.java:252 - это на namespace.getPayloadType().getVersion(), 
т.е. payloadType null?  или namespace, но у вас "через  db.query нормально работает".

Поставьте брейкпойнт пожалуйста, посмотрите, что там.

**Comment by VladislavK777** [comment]
> Пользоваться LIKE можно, примерно так:
> "SELECT * FROM task_view WHERE some_field LIKE '%substring%'"
> 
> > еще интересно, зачем ищется from без ignoreCase if ("FROM".equals(word)) ? Это особенность какая-то?
> 
> Это баг.
> 
> По поводу NPE - как получить доступ к коду примера и к бд?
> Если коннектор не правили под себя, то NPE на Reindexer.java:252 - это на namespace.getPayloadType().getVersion(),
> т.е. payloadType null? или namespace, но у вас "через db.query нормально работает".
> 
> Поставьте брейкпойнт пожалуйста, посмотрите, что там.

Имел ввиду юзать LIKE через билдер запроса нельзя? Только через execSql?

**Comment by steleal** [comment]
> Имел ввиду юзать LIKE через билдер запроса нельзя? Только через execSql?
Через билдер нельзя, Condition LIKE (10) не реализовано.

**Comment by VladislavK777** [comment]
> > Имел ввиду юзать LIKE через билдер запроса нельзя? Только через execSql?
> 
> Через билдер нельзя, Condition LIKE (10) не реализовано.

Надеюсь в будущем реализуете)

Поставил я брейкпоинт, payloadType и правда null. Его как-то заполнять надо?
![image](https://user-images.githubusercontent.com/22882649/130199243-05aefedb-73c1-4b9a-83de-79966d3ce75d.png)

**Comment by steleal** [comment]
Спасибо.
Руками точно не надо, так что баг.
Задачу заведу.

**Comment by steleal** [comment]
Задача заведена, WINKDEV-11680.

**Comment by steleal** [comment]
> > Спасибо.
> > Руками точно не надо, так что баг.
> > Задачу заведу.
> 
> спасибо, а то получается с LIKE не выходит работать((

А киньте ссылочку на гит в Ваш пример, если есть возможность. 
Можно в телеграм @steleal

**Comment by VladislavK777** [comment]
Спасибо за оперативность, а когда планируется релиз?

**Comment by steleal** [comment]
> Спасибо за оперативность, а когда планируется релиз?

Планируем на следующей неделе.
