### ISSUE TITLE
Ошибка при использование IS NULL

### ISSUE THREAD

**Issue by VladislavK777** [Restream/reindexer-java#60]
Добрый день, при попытке выстроить условие is null, возникает эксепшен Binary buffer broken - scan_varint failed: pos=21,len=21
`query1.where("name", Query.Condition.EMPTY).execute();`

![image](https://user-images.githubusercontent.com/22882649/131126776-19a6e605-f75a-4b97-b268-b9bb2fdbd077.png)

Сам индекс в модели
```
@Reindex(name = "name", isSparse = true)
private String name;
```

понял в чем ошибка, в параметр обязательно передать надо.
`query1.where("name", Query.Condition.EMPTY, "");`

вот так работает, строит вот такой запрос SELECT * FROM test_view WHERE name IS NULL ''

Но думаю, что это некорректно, если EMPTY, то параметры не должен проверять.

**Comment by evgeniycheban** [comment]
@VladislavK777 Сделал фикс. Так же для удобства использования `is NULL` условия добавил метод:  
```
public Query<T> isNull(String indexName) {
    return where(indexName, Condition.EMPTY);
}
```

**Comment by VladislavK777** [comment]
спасибо, когда же релиз?)

**Comment by evgeniycheban** [comment]
@VladislavK777 Планирую сегодня выпустить 1.9
