### ISSUE TITLE
Выборка по полям

### ISSUE THREAD

**Issue by VladislavK777** [Restream/reindexer-java#62]
На сервере rx есть возможность сделать выборку по полю, например select status from foo.

В java-connector так же это возможно через вызов нативного запроса через execSql('select status from foo').
Проблема в следующем, что итогом будет итератор основной модели, где поля, которые не указаны в Select будут null, что не совсем удобно, приходится делать переборку итератора, а она очень трудоёмкая. 

Можно ли реализовать так, чтобы возвращалось только запрошенное количество значений, например, `List<String>`, для примитива в единственном количестве. Для несколько полей уже бы запрашивать модель.
Было бы здорово и в билдер сделать такую возможность, например через функцию `.select(<fields>)`.

Например 
```
class Foo {
int id;
String name;
String status;
int typeId;
}
```

```
class SameModel {
int id;
String name;
}
```

`CloseableIterator<SameModel> result = reindexer.query('foo', Foo.class).select('id','name').execute();`
`QueryResultIterator<SameModel> result = reindexer.execSql('select id, status from foo',Foo.class);`

еще может быть такая модель основная с подмоделью.
```
class Foo {
List<Model> models;
}
Model {
List<String> names;
}
```

И тогда было бы здорово вывести все names в одном запросе
`CloseableIterator<String> result = reindexer.query('foo', Foo.class).select('models.names').execute();`
`QueryResultIterator< String > result = reindexer.execSql('select models.names from foo',Foo.class);`

Так же было бы хорошо реализовать через билдер оператор LIKE.

**Comment by evgeniycheban** [comment]
Добавил новый метод `Query<T> select(String... fields)`, куда можно передать поля для выборки, так же добавил метод `<S> CloseableIterator<S> execute(Class<S> itemClass)` куда можно передать класс на который маппить результат запроса.  

Если доработка нужна срочно, то могу собрать snapshot.

**Comment by VladislavK777** [comment]
> @VladislavK777 Добавил новый метод `Query<T> select(String... fields)`, куда можно передать поля для выборки, так же добавил метод `<S> CloseableIterator<S> execute(Class<S> itemClass)` куда можно передать класс на который маппить результат запроса.  
> 
> 
> 
> Если доработка нужна срочно, то могу собрать snapshot.

Класс, спасибо. Пока не критикал выкатывать в мавен. Может еще что-то появится. Там вроде как на серверной стороне будут еще делать функционал, чтобы в условие передавать поля. Для сравнения. Например where endDate>planningEndDate

**Comment by VladislavK777** [comment]
А LIKE в билдер возможно добавить?)

**Comment by evgeniycheban** [comment]
> А LIKE в билдер возможно добавить?)

Да, заведите пожалуйста задачу.
