### ISSUE TITLE
Не работает условие and field is not null

### ISSUE THREAD

**Issue by VladislavK777** [Restream/reindexer-java#68]
Добавить методы isNotNull() и and() в билдер запроса

На данный момент невозможно составить через билдер условие вида "field is not null"

При составлении запроса 
query.not().isNull(fieldName);

получаем
not fieldName is null
без присоединения условия через "and".
Если добавлять как
query.openBracket().not().isNull(fieldName).closeBracket();
то условие not затирается
and (fieldName is null)

При это если вручную прогнать запрос, например:
SELECT FACET(priorityId, priority) 
FROM main_screen_task_view 
WHERE not priorityId IS NULL
получим результаты, включающие пустые значения.

Запрос 
SELECT FACET(priorityId, priority) 
FROM main_screen_task_view 
WHERE priorityId IS not NULL

вернет в свою очередь корректный результат (без пустых значений)

Хотелось бы иметь возможность составлять запрос вида 
fieldName is not null
через билдер с присоединением его через and

**Comment by evgeniycheban** [comment]
@VladislavK777 Добрый день. Вы можете использовать `where("indexName", Condition.ANY)` для `NOT NULL` условия.  
Мы можем добавить метод `isNotNull` для удобства.

**Comment by VladislavK777** [comment]
добавьте пожалуйста для удобства, чтобы билдер выглядит покороче)

**Comment by evgeniycheban** [comment]
@VladislavK777 Добавили метод, войдет в 1.11 релиз. Пока можете пользоваться `Condition.ANY`.

**Comment by VladislavK777** [comment]
Спасибо большое за оперативность:)
