### ISSUE TITLE
Не сохраняются данные в бд после разрыва и восстановления соединения с сервером

### ISSUE THREAD

**Issue by VladislavK777** [Restream/reindexer-java#74]
Кейс.
1) Запустить приложение из https://github.com/VladislavK777/demo-reindexer
2) во время выполнения остановить сервер реиндексера
3) как только сработает эксепшен, снова его запустить, чтобы он продолжил работу

Фактический результат, после остановки, процесс продолжится, но в БД данные не будут попадать, в логах будет отрабатывать два подряд запроса SELECT * FROM main_screen_task_view LIMIT 0

Ошибок при этом никаких нет. 

Версия коннектора 1.10, версия сервера 3.2.4

Здесь, на 35 позиции произошел обрыв, далее он восстановился, процесс пошел дальше.
Видно, что до разрыва, не было запрос вида SELECT * FROM main_screen_task_view LIMIT 0 и записи добавлялись в БД
![image](https://user-images.githubusercontent.com/22882649/139842094-dbd8f2e3-cbb1-447f-b5a7-f8e8adb5f13b.png)

После, в бд данные не добавляются, так и осталось в БД 35 записей
![image](https://user-images.githubusercontent.com/22882649/139842189-9a54640b-e5e3-406c-848f-0c3e4fb74891.png)

А вот если положить
db.openNamespace("test_view", defaultOptions(), TaskView.class);
внутрь цикла, то все ок

**Comment by VladislavK777** [comment]
Когда планируется выпуск в репозиторий?

**Comment by evgeniycheban** [comment]
> Когда планируется выпуск в репозиторий?

На этой или следующей неделе, если нужно срочно, то могу выпустить snapshot.

**Comment by VladislavK777** [comment]
подождем тогда
