### ISSUE TITLE
Не создается композитный индекс

### ISSUE THREAD

**Issue by VladislavK777** [Restream/reindexer-java#80]
Здравствуйте. Возникла проблема с составным индексом. 

При попытке вставить записи в таблицу (предварительно она не была создана вручную) ключ не создается и соответственно вставка записи падает

![image](https://user-images.githubusercontent.com/22882649/143007088-424e3346-7e58-4094-906a-d4c55a4ed177.png)

**Comment by steleal** [comment]
Добрый день, Владислав.

Чтобы воспроизвести проблему, нужно больше информации.
То, что на скриншоте, написано корректно, и namespace с такими полями и настройками индекса создается, а объект вставляется. Т.е. на тестовых данных проблема не воспроизвелась.

Возможно, проблема именно в том, что namespace не был создан?
Namespace создается автоматически при попытке открыть его при настройках по умолчанию:
db.openNamespace(namespaceName, NamespaceOptions.defaultOptions(), ClientContactViewReindexer.class),
но, если настройки не умолчальные, возможно, createStorageIfMissing == false.

**Comment by VladislavK777** [comment]
> Добрый день, Владислав.
> 
> Чтобы воспроизвести проблему, нужно больше информации. То, что на скриншоте, написано корректно, и namespace с такими полями и настройками индекса создается, а объект вставляется. Т.е. на тестовых данных проблема не воспроизвелась.
> 
> Возможно, проблема именно в том, что namespace не был создан? Namespace создается автоматически при попытке открыть его при настройках по умолчанию: db.openNamespace(namespaceName, NamespaceOptions.defaultOptions(), ClientContactViewReindexer.class), но, если настройки не умолчальные, возможно, createStorageIfMissing == false.

Вот так происходит вставка сущности с созданием нэймспейса
![image](https://user-images.githubusercontent.com/22882649/143390713-bb2dd52d-b97d-483a-8c7f-0571a72b09c6.png)

При этом возникает ошибка
ru.rt.restream.reindexer.exceptions.ReindexerException: Trying to modify namespace 'entity_contact_local', but it doesn't contain PK index

И в итоге пусто в индексах
![image](https://user-images.githubusercontent.com/22882649/143390817-5c739c32-33b6-4638-88e5-a85fee472bed.png)

**Comment by steleal** [comment]
Связался, запросил дополнительную информацию.

**Comment by steleal** [comment]
По итогам: 
В демке класс ClientContactViewReindexer имеет (в сумме с вложенными) 50 индексов.
В БД появляется только 44.
Ограничение на количество индексов в одном namespace - 64, до него не дошли (ограничение reindexer, не connector).

Оказалось, что 45 по счету индекс имел [повторяющееся внутри класса имя](https://github.com/VladislavK777/demo-reindexer/blob/05d8ebec4f8ef5b4fc9fb93d7505006cf290a68a/src/main/java/com/example/demo/contact/SpecializationReindexer.java#L22), этот индекс и все после него не были загружены.

**Comment by steleal** [comment]
Todo: Добавить проверку индексов на уникальность при сканировании аннотаций.

**Comment by VladislavK777** [comment]
подскажите, от нас еще нужна информация какая-нибудь? или что-то еще сделать? или проблемы нет, просто мы неверно делали?

**Comment by steleal** [comment]
Нет, никакой информации больше не требуется. 
Во всем разобрались. Наложилось друг на друга три вещи:
1) в одном из классов было два индекса с одинаковым именем ("неверно сделали"), 
2) реиндексер-коннектор не проверяет индексы на уникальность, хотя можно проверить и бросить исключение, чтобы разработчик был в курсе, где ошибка, 
3) реиндексер при создании неймспейса не создает как индекс с дублирующим именем, так и индексы, следующие за ним по порядку (а индексы класса создаются последними).
Наталья по (1) увидела, со своей стороны (2) в задачи поставил (как только разгребусь на основном проекте).
