### ISSUE TITLE
Ошибка если удалить namespace

### ISSUE THREAD

**Issue by VladislavK777** [Restream/reindexer-java#81]
Добрый день, обнаружили еще такую проблему, или может не проблему. Если приложение запустить и удалить руками namespace, то приложение падает при обращении к этому namespace. То есть не пытается снова его создать.

**Comment by evgeniycheban** [comment]
Добрый день. Это нормальное поведение, namespace создается только 1 раз вызовом метода `openNamespace`. 
Повторный вызов `openNamespace` вернет уже созданный объект `Namespace`, если namespace был удален в обход коннектора, то нужно перезапустить приложение чтобы он был снова создан. 
Для того чтобы была возможность создать повторно namespace методом `openNamespace` нужно использовать метод коннектора `dropNamespace`.

Тикет закрываю, т.к это ожидаемое поведение коннектора.
