### ISSUE TITLE
Доработка сравнения полей

### ISSUE THREAD

**Issue by VladislavK777** [Restream/reindexer-java#82]
Добрый день, серверная часть reindexer обновилась до 3.3.0 и там вышла долгожданная фича сравнения по полям в запросе.

![image](https://user-images.githubusercontent.com/22882649/144215347-f51c5ae2-1e6d-4338-a378-2b4e3872d012.png)

Хотелось бы чтобы в коннекторе доработали возможность составлять такие запросы через функционал .where(), сейчас такие запросы можно выполнить при помощи execSql. 
`namespace.execSql("select * from test_view where create > date")`

Но это не совсем подходит, так как запрос формируется в нескольких местах.  Это очень нужно на самом деле( Ради этого как раз и просили доработать серверную часть.

**Comment by evgeniycheban** [comment]
@VladislavK777 Добавили новый метод
`whereBetweenFields(String firstField, Condition condition, String secondField)`

Войдет в 1.12 релиз.

**Comment by VladislavK777** [comment]
> 

а когда релиз? Если можно попросить оповестить плиз)

**Comment by evgeniycheban** [comment]
В пятницу сделаем релиз.

**Comment by evgeniycheban** [comment]
@VladislavK777 Выпустили релиз 1.12
