### ISSUE TITLE
Reconnect to RX

### ISSUE THREAD

**Issue by FilKys** [Restream/reindexer-java#85]
В какой-то момент CPU сервиса, в котором используется RX-connector, очень сильно начинает потребляться и падает коннект к RX. Вылетают ошибки по Ping и RequestTimeOut. Сервис при этом ни как не нагружался. Реконект к RX не происходит.

**Comment by steleal** [comment]
Задачу завел. Если есть способ воспроизвести - буду признателен.

**Comment by FilKys** [comment]
Способа воспроизвести нет...

**Comment by steleal** [comment]
Воспроизвести на актуальной версии коннектора (rx-1.12) не удалось.
Уточнил обстоятельства, при которых было падение:
JDK liberica 11.0.13
rx-connector - 1.9
RX - предположительно 3.2.5

Похоже, что сначала пропал коннект (по сетевым причинам), а потом коннектор не смог переподключиться.
Это очень похоже на баг [gh-74](https://github.com/Restream/reindexer-java/issues/74), закрытый в rx-connector 1.11.
Также по дополнительной информации,  работало 3 сервиса в тот момент, 2 на версии 1.9, 1 на версии 1.11 и на версии 1.9 падали, а 1.11 нет.

Предлагаю обновить версию коннектора до актуальной и, если до 10 марта 2022 года на 1.12 падений не будет, закрыть issue как повтор  [gh-74](https://github.com/Restream/reindexer-java/issues/74).

**Comment by evgeniycheban** [comment]
@FilKys Попробуйте обновиться до актуальной версии, если проблема повторится, то заведите пожалуйста новый тикет, этот закрываю.
