### ISSUE TITLE
Падение тестов для rx 4.2.0

### ISSUE THREAD

**Issue by belkalite** [Restream/reindexer-java#86]
Запущены тесты для java-connector в докере ubuntu 20.04 с Reindexer v4.2.0.

Происходит падение разного количества тестов с логом: 
[javalog.txt](https://github.com/Restream/reindexer-java/files/8130976/javalog.txt)

При отдельном  запуске падающего  теста трейс такой: http://paste.restr.im/86342/

Для тестирования устанавливался пакет Reindexer 4.2.0 для ubuntu 20.04 с фиксом для builtin.

**Comment by steleal** [comment]
Завели задачу: https://jira.iptv.rt.ru/browse/WINKDEV-14025
