### ISSUE TITLE
UUID

### ISSUE THREAD

**Issue by IISannikov** [Restream/reindexer-java#96]
В Reindexer добавили поддержку UUID

1. Для этого в ctag добавили type UUID = 8, теперь ctag имеет следующий формат:
```
|31     29|28        25|24     15|14     3|2     0|
|  TYPE1  |  RESERVED  |  FIELD  |  NAME  | TYPE0 |
TYPE0 and TYPE1 - 6bit  type: one of TAG_XXXX
NAME - 12bit index+1 of field name in tagsMatcher (0 if no name)
FIELD - 10bit index+1 of field in reindexer Payload (0 if no field)
```
type увеличен с 3 до 6 бит и разбит на 2 подполя: младшие 3 бита хранятся в младших 3 битах ctag'а,  а старшие 3 бита - в старших 3 битах ctag'а 

2. Строковое индексное поле, содержащее UUID, можно пометить флажком isUuid = true
  ```java
  @Reindex(name = "id", isUuid = true, type = HASH)
  private String id;
```
Поддерживается только индекс типа hash (в будущем планируем это расширить)
в этом поле можно хранить только uuid в строковом формате
UUID Variant 0 не поддерживается
при передаче значений этого поля в Reindexer и из Reindexer'a ctag для него имеет type UUID = 8
а строковое значение UUID преобразуется в два 64 битных числа, записанных последовательно (можно воспринимать как одно 128 число)
пример преобразования строка -> число можно посмотреть [здесь C++](https://github.com/Restream/reindexer/blob/267d053da1c46153e5d45ba5dbbe6371c9c23ae9/cpp_src/core/keyvalue/uuid.cc#L14) или [здесь Golang](https://github.com/Restream/reindexer/blob/267d053da1c46153e5d45ba5dbbe6371c9c23ae9/cjson/encoder.go#L226)
а в обратную сторону - [здесь C++](https://github.com/Restream/reindexer/blob/267d053da1c46153e5d45ba5dbbe6371c9c23ae9/cpp_src/core/keyvalue/uuid.cc#L92) или [здесь Golang](https://github.com/Restream/reindexer/blob/267d053da1c46153e5d45ba5dbbe6371c9c23ae9/cjson/creflect.go#L109)

**Comment by steleal** [comment]
Создана задача WINKDEV-13992.
